import xml.etree.ElementTree as ET
from xml.dom import minidom
import os
import argparse
import json
import re

# --- Argument Parsing ---
parser = argparse.ArgumentParser(description='Figma (JSON) to JUCE XML layout converter')
parser.add_argument('input_json', type=str, help='Path to the .json file generated by fig2sketch/fig2json')
parser.add_argument('--output', type=str, default='juce_layout.xml', help='Output XML file')
parser.add_argument('--frame_name', required=True, type=str, nargs='+', help='The name(s) of the top-level Frame(s) to export')

args = parser.parse_args()

# --- Configuration ---
INPUT_JSON_FILE = args.input_json
OUTPUT_XML_FILE = args.output
TARGET_FRAME_NAMES = args.frame_name

# --- Helper Functions ---

def sanitize_for_xml_tag(name):
    """Sanitizes a string to be a valid XML tag name."""
    s = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    if s and s[0].isdigit():
        s = '_' + s
    return s

def find_frame(node, name):
    """Recursively searches for a frame with a specific name in the JSON tree."""
    # Check if current node matches
    if node.get('name') == name and node.get('type') in ['FRAME', 'GROUP', 'COMPONENT', 'SYMBOL_MASTER']:
        return node
    
    # Recurse children
    if 'children' in node:
        for child in node['children']:
            found = find_frame(child, name)
            if found:
                return found
    return None

def format_color(color_obj):
    """Formats a JSON color object into an #AARRGGBB hex string."""
    # Input expected: {'r': 1.0, 'g': 1.0, 'b': 1.0, 'a': 1.0}
    r = int(color_obj.get('r', 0) * 255)
    g = int(color_obj.get('g', 0) * 255)
    b = int(color_obj.get('b', 0) * 255)
    a = int(color_obj.get('a', 1) * 255)
    return f"#{a:02x}{r:02x}{g:02x}{b:02x}"

def format_float(value):
    """Formats a float value to 3 decimal places, removing trailing zeros.
    Preserves decimal point for whole numbers (e.g., 1.0 stays as '1.0')."""
    # If it's a whole number, format with one decimal place to preserve the float type
    if isinstance(value, float) and value == int(value):
        return f"{value:.1f}"
    # Otherwise format to 3 decimal places and strip trailing zeros
    return f"{value:.3f}".rstrip('0').rstrip('.')

def process_gradient(paint, prefix):
    """Processes a gradient paint object."""
    attributes = {}
    paint_type_map = {
        'GRADIENT_LINEAR': 'linear',
        'GRADIENT_RADIAL': 'radial',
        'GRADIENT_ANGULAR': 'angular',
        'GRADIENT_DIAMOND': 'diamond',
    }
    gradient_type = paint_type_map.get(paint['type'])
    if not gradient_type: return {}

    attributes[f'{prefix}-gradient-type'] = gradient_type

    # Handle new format: extract gradient direction from transform matrix
    if 'transform' in paint and len(paint['transform']) >= 2:
        transform = paint['transform']
        # Transform matrix: [[m00, m01, tx], [m10, m11, ty], [0, 0, 1]]
        # For linear gradients, the gradient goes from (0,0) to (1,0) in gradient space
        # We need to transform these points to normalized coordinates (0-1 range)
        
        m00, m01 = transform[0][0], transform[0][1]
        m10, m11 = transform[1][0], transform[1][1]
        tx = transform[0][2] if len(transform[0]) > 2 else 0.0
        ty = transform[1][2] if len(transform[1]) > 2 else 0.0
        
        # Transform start point (0, 0) in gradient space to normalized coordinates
        start_x = m00 * 0 + m01 * 0 + tx
        start_y = m10 * 0 + m11 * 0 + ty
        
        # Transform end point (1, 0) in gradient space to normalized coordinates
        end_x = m00 * 1 + m01 * 0 + tx
        end_y = m10 * 1 + m11 * 0 + ty
        
        # Clamp to 0-1 range for normalized coordinates
        start_x = max(0.0, min(1.0, start_x))
        start_y = max(0.0, min(1.0, start_y))
        end_x = max(0.0, min(1.0, end_x))
        end_y = max(0.0, min(1.0, end_y))
        
        # Format to 3 decimal places, removing trailing zeros
        start_str = f"{format_float(start_x)},{format_float(start_y)}"
        end_str = f"{format_float(end_x)},{format_float(end_y)}"
        
        attributes[f'{prefix}-gradient-start'] = start_str
        attributes[f'{prefix}-gradient-end'] = end_str
    
    # Handle old format (gradientHandlePositions) for backward compatibility
    elif 'gradientHandlePositions' in paint and len(paint['gradientHandlePositions']) >= 2:
        start_pos = paint['gradientHandlePositions'][0]
        end_pos = paint['gradientHandlePositions'][1]
        attributes[f'{prefix}-gradient-start'] = f"{format_float(start_pos.get('x',0))},{format_float(start_pos.get('y',0))}"
        attributes[f'{prefix}-gradient-end'] = f"{format_float(end_pos.get('x',0))},{format_float(end_pos.get('y',0))}"

    # Handle new format: stops array
    if 'stops' in paint:
        stops = [f"{format_color(stop['color'])}:{format_float(stop['position'])}" for stop in paint['stops']]
        attributes[f'{prefix}-gradient-stops'] = ",".join(stops)
    # Handle old format (gradientStops) for backward compatibility
    elif 'gradientStops' in paint:
        stops = [f"{format_color(stop['color'])}:{format_float(stop['position'])}" for stop in paint['gradientStops']]
        attributes[f'{prefix}-gradient-stops'] = ",".join(stops)

    return attributes

def get_layout_properties(node):
    """Extracts relative x, y, width, height from the new JSON format."""
    x, y, w, h = 0, 0, 0, 0
    
    node_type = node.get('type')
    
    # 1. Get transform matrix components
    # Matrix is usually [[m00, m01, tx], [m10, m11, ty], [0, 0, 1]]
    m00, m01, tx = 1, 0, 0
    m10, m11, ty = 0, 1, 0
    
    if 'transform' in node and len(node['transform']) >= 2:
        m00 = node['transform'][0][0]
        m01 = node['transform'][0][1]
        tx = node['transform'][0][2] if len(node['transform'][0]) > 2 else 0
        m10 = node['transform'][1][0]
        m11 = node['transform'][1][1]
        ty = node['transform'][1][2] if len(node['transform'][1]) > 2 else 0
    
    # 2. Get local size
    local_w, local_h = 0, 0
    if 'size' in node:
        local_w = node['size']['x']
        local_h = node['size']['y']
    
    # 3. For lines, calculate bounding box from transformed endpoints
    # Lines can be rotated, so we need to transform the line endpoints
    # and compute the axis-aligned bounding box
    if node_type == 'LINE':
        # Line goes from (0,0) to (local_w, local_h) in local space
        # Transform both endpoints through the matrix
        p0_x = m00 * 0 + m01 * 0 + tx
        p0_y = m10 * 0 + m11 * 0 + ty
        p1_x = m00 * local_w + m01 * local_h + tx
        p1_y = m10 * local_w + m11 * local_h + ty
        
        # Compute axis-aligned bounding box
        x = min(p0_x, p1_x)
        y = min(p0_y, p1_y)
        w = abs(p1_x - p0_x)
        h = abs(p1_y - p0_y)
    else:
        # For non-line elements, use translation + size (rotation not typically applied)
        x = tx
        y = ty
        w = local_w
        h = local_h
        
    return x, y, w, h

def extract_rotary_slider_style(children):
    """Extracts rotary slider style attributes from circle/arc children."""
    attributes = {}
    processed_child_names = set()

    for child in children:
        child_name = child.get('name', '')

        # Process "circle" child
        if child_name == 'circle':
            processed_child_names.add('circle')
            # Extract fill color
            fills = child.get('fillPaints', [])
            if fills:
                top_fill = next((f for f in reversed(fills) if f.get('visible', True)), None)
                if top_fill and top_fill['type'] == 'SOLID':
                    attributes['circleFillColour'] = format_color(top_fill['color'])

            # Extract stroke color and width
            strokes = child.get('strokePaints', [])
            if strokes:
                top_stroke = next((s for s in reversed(strokes) if s.get('visible', True)), None)
                if top_stroke and top_stroke['type'] == 'SOLID':
                    attributes['circleStrokeColour'] = format_color(top_stroke['color'])

            if 'strokeWeight' in child and child['strokeWeight'] > 0:
                attributes['circleStrokeWidth'] = format_float(child['strokeWeight'])

        # Process "arc_active" child
        elif child_name == 'arc_active':
            processed_child_names.add('arc_active')
            # Extract stroke color and width (stroke only)
            strokes = child.get('strokePaints', [])
            if strokes:
                top_stroke = next((s for s in reversed(strokes) if s.get('visible', True)), None)
                if top_stroke and top_stroke['type'] == 'SOLID':
                    attributes['arcActiveColour'] = format_color(top_stroke['color'])

            if 'strokeWeight' in child and child['strokeWeight'] > 0:
                attributes['arcActiveWidth'] = format_float(child['strokeWeight'])

        # Process "arc_bg" child
        elif child_name == 'arc_bg':
            processed_child_names.add('arc_bg')
            # Extract stroke color and width (stroke only)
            strokes = child.get('strokePaints', [])
            if strokes:
                top_stroke = next((s for s in reversed(strokes) if s.get('visible', True)), None)
                if top_stroke and top_stroke['type'] == 'SOLID':
                    attributes['arcBgColour'] = format_color(top_stroke['color'])

            if 'strokeWeight' in child and child['strokeWeight'] > 0:
                attributes['arcBgWidth'] = format_float(child['strokeWeight'])

    return attributes, processed_child_names

def process_node(node, parent_xml_element):
    """
    Recursively processes a node from the JSON, creates an XML element, 
    adds attributes, and processes children.
    """
    name = node.get('name', 'Untitled')
    node_type = node.get('type')
    
    # Calculate relative coordinates directly from transform/size
    rel_x, rel_y, width, height = get_layout_properties(node)
    
    print(f"Processing node: {name} (Type: {node_type})")

    # --- Handling Instance Frames (Special Logic) ---
    if name.endswith('_instance_frame'):
        print(f"-> Found instance frame: {name}. Processing as layout container.")
        attributes = {
            "name": name,
            # "x": str(round(rel_x)),
            # "y": str(round(rel_y)),
            # "width": str(round(width)),
            # "height": str(round(height))
            "x": str(format_float(rel_x)),
            "y": str(format_float(rel_y)),
            "width": str(format_float(width)),
            "height": str(format_float(height))
        }
        
        # Check layout props if they exist in this JSON format
        if 'layoutMode' in node and node['layoutMode'] != 'NONE': 
            attributes['layout-mode'] = node['layoutMode'].lower()
        if 'itemSpacing' in node: 
            attributes['layout-gap'] = str(round(node['itemSpacing']))
        if 'primaryAxisAlignItems' in node: 
            attributes['layout-justify'] = node['primaryAxisAlignItems'].lower().replace('_', '-')
        if 'counterAxisAlignItems' in node: 
            attributes['layout-align-items'] = node['counterAxisAlignItems'].lower().replace('_', '-')
        
        ET.SubElement(parent_xml_element, 'InstanceFrame', attributes)
        return

    # --- Standard Attributes ---
    attributes = {
        "name": name,
        # "x": str(round(rel_x)), 
        # "y": str(round(rel_y)),
        # "width": str(round(width)), 
        # "height": str(round(height))
        "x": str(format_float(rel_x)),
        "y": str(format_float(rel_y)),
        "width": str(format_float(width)),
        "height": str(format_float(height))
    }

    if 'opacity' in node and node['opacity'] < 1.0: 
        attributes['opacity'] = format_float(node['opacity'])
    
    # Corner Radius
    if 'cornerRadius' in node and node['cornerRadius'] > 0: 
        attributes['cornerRadius'] = str(round(node['cornerRadius']))
    elif 'rectangleTopLeftCornerRadius' in node:
        # Fallback if uniform radius isn't set but individual ones are
        attributes['cornerRadius'] = str(round(node.get('rectangleTopLeftCornerRadius', 0)))

    # --- Fills (fillPaints) ---
    has_image_fill = False
    fills = node.get('fillPaints', [])
    if fills:
        # Find top visible fill
        top_fill = next((f for f in reversed(fills) if f.get('visible', True)), None)
        if top_fill:
            if top_fill['type'] == 'SOLID': 
                attributes['fillColour'] = format_color(top_fill['color'])
            elif top_fill['type'].startswith('GRADIENT'): 
                attributes.update(process_gradient(top_fill, 'fill'))
            elif top_fill['type'] == 'IMAGE': 
                has_image_fill = True

    # --- Strokes (strokePaints) ---
    strokes = node.get('strokePaints', [])
    if strokes:
        top_stroke = next((s for s in reversed(strokes) if s.get('visible', True)), None)
        if top_stroke:
            if top_stroke['type'] == 'SOLID': 
                attributes['strokeColour'] = format_color(top_stroke['color'])
            elif top_stroke['type'].startswith('GRADIENT'): 
                attributes.update(process_gradient(top_stroke, 'stroke'))
            
            if 'strokeWeight' in node and node['strokeWeight'] > 0:
                attributes['strokeWeight'] = format_float(node['strokeWeight'])

    # --- Text Specifics ---
    if node_type == 'TEXT':
        # Text Content
        if 'textData' in node and 'characters' in node['textData']:
            attributes['text'] = node['textData']['characters']
        elif 'characters' in node: # Fallback
            attributes['text'] = node['characters']
            
        # Font Info
        font_name = node.get('fontName', {}) 
        if not font_name and 'style' in node: font_name = node.get('style', {}) # Fallback location

        if 'family' in font_name: attributes['fontName'] = font_name['family']
        
        # Font Style construction
        font_style_parts = []
        style_str = font_name.get('style', '')
        if 'Bold' in style_str: font_style_parts.append("Bold")
        if 'Light' in style_str: font_style_parts.append("Light")
        if 'Italic' in style_str: font_style_parts.append("Italic")
        if 'Medium' in style_str: font_style_parts.append("Medium")
        # Add pure weight mapping if available in raw data, otherwise rely on style string
        
        if font_style_parts: 
            attributes['fontType'] = " ".join(font_style_parts)
        
        if 'fontSize' in node: 
            attributes['fontSize'] = str(round(node['fontSize']))
            
        if 'textAlignHorizontal' in node: 
            attributes['textAlignHorizontal'] = node['textAlignHorizontal'].lower()
        # else:
        #     attributes['textAlignHorizontal'] = 'left'

        if 'textAlignVertical' in node:
            attributes['textAlignVertical'] = node['textAlignVertical'].lower()
        # else:
        #     attributes['textAlignVertical'] = 'top'

        if node.get('textDecoration', '') == 'UNDERLINE':
            attributes['textDecoration'] = 'underline'

    # --- Rotary Slider Handling (Special Logic) ---
    if name.endswith('_rotary_slider'):
        print(f"-> Found rotary slider: {name}. Extracting properties from children.")
        
        children = node.get('children', [])

        # New structure: style elements live inside slider_widget
        slider_widget_node = next((c for c in children if c.get('name', '') == 'slider_widget'), None)

        if slider_widget_node:
            widget_children = slider_widget_node.get('children', [])
            widget_style_attrs, widget_processed = extract_rotary_slider_style(widget_children)
            attributes.update(widget_style_attrs)

            # Create RotarySlider element
            current_xml_element = ET.SubElement(parent_xml_element, 'RotarySlider', attributes)

            # Create SliderWidget element with layout info
            widget_x, widget_y, widget_w, widget_h = get_layout_properties(slider_widget_node)
            widget_attributes = {
                "name": slider_widget_node.get('name', 'slider_widget'),
                "x": str(format_float(widget_x)),
                "y": str(format_float(widget_y)),
                "width": str(format_float(widget_w)),
                "height": str(format_float(widget_h))
            }
            widget_attributes.update(widget_style_attrs)
            slider_widget_element = ET.SubElement(current_xml_element, 'SliderWidget', widget_attributes)

            # Process remaining slider_widget children (excluding style elements)
            for child in widget_children:
                if child.get('name', '') not in widget_processed:
                    process_node(child, slider_widget_element)

            # Process remaining rotary slider children (excluding slider_widget)
            for child in children:
                if child.get('name', '') != 'slider_widget':
                    process_node(child, current_xml_element)

            return

        # Old structure: style elements are direct children
        style_attrs, processed_child_names = extract_rotary_slider_style(children)
        attributes.update(style_attrs)

        # Create RotarySlider element
        current_xml_element = ET.SubElement(parent_xml_element, 'RotarySlider', attributes)

        # Process remaining children (excluding the ones we already processed)
        for child in children:
            if child.get('name', '') not in processed_child_names:
                process_node(child, current_xml_element)

        return

    # --- Tag Determination ---
    tag = 'Object'
    parent_tag = parent_xml_element.tag if parent_xml_element is not None else None
    
    if has_image_fill: tag = 'Object'
    elif parent_tag == 'TextEditor':
        if name == 'text_editor_box': tag = 'TextEditorBox'
        elif name == 'text_editor_suggestion': tag = 'TextEditorSuggestion'
        elif name == 'text_editor_entry': tag = 'TextEditorEntry'
    elif parent_tag == 'TextButton':
        if name == 'btn_bg': tag = 'ButtonBackground'
        elif name == 'btn_text': tag = 'ButtonText'
    elif parent_tag == 'RotarySlider':
        if name == 'slider_widget': tag = 'SliderWidget'
        elif name == 'slider_value_text': tag = 'SliderValueText'
    elif parent_tag == 'HyperlinkButton':
        if name == 'hyperlink_text': tag = 'HyperlinkText'
        elif name == 'hyperlink_bg': tag = 'HyperlinkBackground'
    elif name.endswith('_img'): tag = 'Image'
    elif name.endswith('_text_btn'): tag = 'TextButton'
    elif name.endswith('_img_btn'): tag = 'ImageButton'
    elif name.endswith('_text_editor'): tag = 'TextEditor'
    elif name.endswith('_hyperlink'): tag = 'HyperlinkButton'
    elif name.endswith('_auto_label'):
        tag = 'AutoLabel'
        attributes['auto'] = 'true'
    elif node_type == 'TEXT': tag = 'Label'
    elif node_type == 'LINE': tag = 'Line'
    elif node_type in ['RECTANGLE', 'ROUNDED_RECTANGLE']: tag = 'Rectangle'
    elif node_type == 'ELLIPSE': tag = 'Ellipse'

    # Component Handling
    if node_type in ['COMPONENT', 'SYMBOL_MASTER']:
        tag = 'ComponentState'
    elif node_type == 'COMPONENT_SET':
        tag = 'Component'

    # Add multiline property for multiline text editors
    if tag == 'TextEditor' and name.endswith('_multiline_text_editor'):
        attributes['multiline'] = 'true'
    
    # Add isToggleable property for toggle image buttons
    if tag == 'ImageButton' and name.endswith('_toggle_img_btn'):
        attributes['isToggleable'] = 'true'

    current_xml_element = ET.SubElement(parent_xml_element, tag, attributes)

    # --- Recursion ---
    if 'children' in node:
        for child in node['children']:
            process_node(child, current_xml_element)

def find_and_process_components(node, components_xml_parent):
    """
    Recursively finds 'COMPONENT', 'SYMBOL_MASTER' or 'COMPONENT_SET' nodes.
    """
    node_type = node.get('type')
    
    if node_type in ['COMPONENT', 'COMPONENT_SET', 'SYMBOL_MASTER']:
        process_node(node, components_xml_parent)
    
    # Recurse through children unless the node itself is a component
    # (process_node handles the internals of the component)
    if node_type not in ['COMPONENT', 'COMPONENT_SET', 'SYMBOL_MASTER'] and 'children' in node:
        for child in node['children']:
            find_and_process_components(child, components_xml_parent)

# --- Main script ---
def main():
    if not os.path.exists(INPUT_JSON_FILE):
        print(f"Error: JSON file not found at {INPUT_JSON_FILE}")
        exit()

    try:
        with open(INPUT_JSON_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        exit()

    # Determine root document node
    if 'document' in data:
        document = data['document']
    else:
        # Fallback if the file is just the document object directly
        document = data

    root = ET.Element("JUCELayout")
    components_root = ET.SubElement(root, "Components")
    
    print("\n--- Searching for Component Definitions ---")
    if 'children' in document:
        for page in document['children']:
            if page.get('type') == 'CANVAS':
                find_and_process_components(page, components_root)
    print("--- Finished Component Search ---\n")

    for frame_name in TARGET_FRAME_NAMES:
        target_frame = find_frame(document, frame_name)
        
        if not target_frame:
            print(f"Warning: Could not find a Frame named '{frame_name}' in your file. Skipping.")
            continue
            
        print(f"--- Processing Target Frame: {frame_name} ---")
        # In the old script, we passed absoluteBoundingBox. 
        # Here, we don't need it because children calculate their own relative pos.
        process_node(target_frame, root)
        print(f"--- Finished Processing Target Frame ---\n")

    xml_string = ET.tostring(root, 'utf-8')
    reparsed = minidom.parseString(xml_string)
    pretty_xml = reparsed.toprettyxml(indent="  ")

    try:
        with open(OUTPUT_XML_FILE, "w", encoding='utf-8') as f:
            f.write(pretty_xml)
        print(f"Successfully exported layout to {os.path.abspath(OUTPUT_XML_FILE)}")
    except IOError as e:
        print(f"Error writing to file: {e}")

if __name__ == "__main__":
    main()
